Es6 classes
dotkeenan/lfz-alumni-code-solutions pull request #4
Opened 2021-10-19 05:49 UTC by dotkeenan

![es6-classes](https://user-images.githubusercontent.com/18623005/137851248-31b8992d-1540-4083-af84-d95d3d96225c.png)

2021-10-19 16:40 UTC, thebearingedge requested changes

2021-10-19 16:40 UTC, thebearingedge commented on es6-classes/example-class.js
> +}
This code doesn't parse. You can leave out the constructor for a simple class.

```js
class ExampleClass {
}
```

2021-10-19 22:59 UTC, dotkeenan commented on es6-classes/example-class.js
> +}
fixed!

2021-10-19 23:00 UTC, dotkeenan commented
![image](https://user-images.githubusercontent.com/18623005/138002064-a9be928a-0907-4e6b-8045-75b26bbfbabd.png)

2021-10-20 02:19 UTC, thebearingedge approved these changes

2021-10-20 05:31 UTC, merged